#NodePort
apiVersion: apps/v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selectro:
    app: nginx
  ports:
    port: 80
    targetport: 80
    nodePort: 8080