apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-dd-account-hd-5g
  annotations:
    volume.beta.kubernetes.io/storage-class: accounthdd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi