apiVersion: v1
kind: Pod
spec:
  volumes:
    -name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: docker-socket
  containers:
  - name: docker
    image: docker
    comand: ["sleep"]
    args: ["100000"]
    volumeMounts:
      -name: docker-socket
        mountPath: /var/run/docker.sock